# apiVersion: extensions/v1beta1
# kind: Deployment
# metadata:
#   name: coffee-demo-app
#   labels:
#     name: coffee-demo-app
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         name: coffee-demo-app
#     spec:
#       containers:
#       - name: coffee-demo-app
#         image: cgascoig/coffee-demo-app
#         ports:
#         - name: https
#           containerPort: 5000

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: nginx
  # namespace: ccp
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path: /nginx