apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffee-demo-app
  namespace: coffee-demo
  labels:
    name: coffee-demo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: coffee-demo-app
    spec:
      containers:
      - name: coffee-demo-app
        image: cgascoig/coffee-demo-app:latest
        imagePullPolicy: Always
        command: 
          - /coffee-demo-app
          - -verbose
          - -mongo
          - mongodb://coffee-demo-mongo:27017
        ports:
        - name: http
          containerPort: 5000
        volumeMounts:
        - name: dialogflow-key
          mountPath: "/keys"
          readOnly: true
      volumes:
      - name: dialogflow-key
        secret: 
          secretName: dialogflow-key
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-demo-app
  namespace: coffee-demo
  labels:
    name: coffee-demo-app
spec:
  ports:
    # the port that this service should serve on
  - port: 5000
    targetPort: 5000
  selector:
    name: coffee-demo-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffee-demo-reporting
  namespace: coffee-demo
  labels:
    name: coffee-demo-reporting
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: coffee-demo-reporting
    spec:
      containers:
      - name: coffee-demo-reporting
        image: cgascoig/coffee-demo-reporting:latest
        imagePullPolicy: Always
        command: 
          - /coffee-demo-reporting
          - -verbose
          - -mongo
          - mongodb://coffee-demo-mongo:27017
        ports:
        - name: http
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-demo-reporting
  namespace: coffee-demo
  labels:
    name: coffee-demo-reporting
spec:
  ports:
    # the port that this service should serve on
  - port: 5000
    targetPort: 5000
  selector:
    name: coffee-demo-reporting
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffee-demo-front-end
  namespace: coffee-demo
  labels:
    name: coffee-demo-front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: coffee-demo-front-end
    spec:
      containers:
      - name: coffee-demo-front-end
        image: cgascoig/coffee-demo-front-end:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-demo-front-end
  namespace: coffee-demo
  labels:
    name: coffee-demo-front-end
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: coffee-demo-front-end
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffee-demo-mongo
  namespace: coffee-demo
  labels:
    name: coffee-demo-mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: coffee-demo-mongo
    spec:
      containers:
      - name: coffee-demo-mongo
        image: mongo
        imagePullPolicy: Always
        ports:
        - name: mongo
          containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-demo-mongo
  namespace: coffee-demo
  labels:
    name: coffee-demo-mongo
spec:
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017
  selector:
    name: coffee-demo-mongo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # Comment out the following nginx-related annotations when deploying to GKE
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: coffee-demo-front-end
  namespace: coffee-demo
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: coffee-demo-front-end
          servicePort: 80
        # Comment out the following nginx-related annotations when deploying to GKE (GKE ingress doesn't support path rewrite)
        path: /coffee-demo