apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: coffee-demo-app
  labels:
    name: coffee-demo-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: coffee-demo-app
    spec:
      containers:
      - name: coffee-demo-app
        image: cgascoig/coffee-demo-app:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        volumeMounts:
        - name: dialogflow-key
          mountPath: "/keys"
          readOnly: true
      volumes:
      - name: dialogflow-key
        secret: 
          secretName: dialogflow-key
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-demo-app
  labels:
    name: coffee-demo-app
spec:
  ports:
    # the port that this service should serve on
  - port: 5000
    targetPort: 5000
  selector:
    name: coffee-demo-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: coffee-demo-app
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: coffee-demo-app
          servicePort: 5000
        path: /coffee-demo-app